### ISSUE TITLE
Bounce crash

### ISSUE THREAD

**Issue by NotLe0n** [NotLe0n/CameraControl#3]
The game crashes when the tracker bounces while in a spline curve.

Logs:
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at CameraControl.CameraSystem.ModifyScreenPosition() in CameraControl\CameraSystem.cs:line 61
   at Terraria.ModLoader.SystemLoader.ModifyScreenPosition() in tModLoader\Terraria\ModLoader\SystemLoader.cs:line 118
   at Terraria.Main.DoDraw_UpdateCameraPosition() in tModLoader\Terraria\Main.cs:line 49234
   at Terraria.Main.DoDraw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 48269
```

**Comment by NotLe0n** [comment]
Probably fixed with 6c2fc645efdcea6fd44dc6ad8ab50726aa6e779e
